spring:
  application:
    name: maverick-chatbot
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <Your API Key>
