spring:
  application:
    name: maverick-chatbot
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <Your API Key>
asr:
  vendor: sherpa-onnx
  sherpa:
    base-url: http://localhost:8081
    endpoint: /v1/asr-transcribe
tts:
  vendor: py3-tts
  cosyvoice:
    base-url: http://localhost:8082
    endpoint: /v1/tts-synthesize
  default-voice: zh
