spring:
  application:
    name: maverick-chatbot
  profiles:
    active: local
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: <Your API Key>
      embedding-model:
        model-name: text-embedding-v4
        api-key: <Your API Key>
asr:
  vendor: sherpa-onnx
  sherpa:
    base-url: http://localhost:8081
    endpoint: /v1/asr-transcribe
tts:
  vendor: volc-demo
  volc:
    ws-url: wss://openspeech.bytedance.com/api/v1/tts/ws_binary
    api-url: https://openspeech.bytedance.com/tts
    app-id: 9838143164
    access-token: 
    sk: 
    voice-id: 
    format: mp3
    auth-header-prefix: "Bearer "
rag:
  chroma:
    base-url: http://localhost:8000
    collection: maverick_docs
